### ISSUE TITLE
Eject or clean the sample demo application

### ISSUE THREAD

**Issue by ngoquoc** [ngoquoc/react-boilerplate-demo#2]
It would be super helpful and useful to have a script to clean the sample demo application from this boilerplate, so we can easily start hacking new project.
It's good that this repo contains a sample app for learning/experimental purpose, but when I tried to start with new project with this template, it's a problem. Because there are so many implementations of specific project, that I don't want to have in my new project.

Thanks!

**Comment by bl5ck** [comment]
Below is the progress of this proposal:
- [x] Example ejecting guide.
- [ ] Eject script based on the guide.

**Comment by bl5ck** [comment]
Implemented.
